dist: trusty

services:
  - docker

env:
  global:
    - NAME=tuimac/openvpn
    - PORT=30001

before_script: cd images/x64

jobs:
  include:
    - stage: 'Run docker container'
      name: 'Run openvpn container'
      script:
        - docker build -t ${NAME} .
        - docker volume create ${NAME}
        - docker run -itd --name ${NAME} -v ${NAME}:/etc/openvpn -p ${PDRT}:1194/udp -p ${PORT}:1194/tcp --cap-add NET_ADMIN --env-file env.list ${NAME}
        - sleep 1
        - "[[ ! -z $(docker ps -a | grep Exited) ]] && { echo 'Start container had been failed!!'; exit 1; }"
        - "for i in {0..4}; do curl http://localhost:${PORT}; sleep 10; done"
        - "[[ $? -ne 0 ]] && { echo 'failure!!'; exit 1; }"
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push ${NAME} 
