language: bash
dist: focal
sudo: required
services:
  - docker
env:
  global:
    - NAME=openvpn
    - PORT=30000
jobs:
  include:
    - stage: 'Test running container'
      before_script: cd builds
      env:
        - IMAGE=tuimac/openvpn
      script: docker build -t ${IMAGE} . || travis_terminate 1;
      name: 'Build docker image'
    - script: docker volume create ${NAME} || travis_terminate 1;
      name: 'Create docker volume'
    - script: docker run -itd --name ${NAME} -v ${NAME}:/etc/openvpn -p ${PORT}:1194/udp -p ${PORT}:1194/tcp --cap-add NET_ADMIN --env-file env.list -h ${NAME} --network=bridge ${IMAGE} || travis_terminate 1;
      name: 'Create docker container'
    - script: sleep 3 && for i in {0..4}; do curl http://localhost:${PORT}; sleep 10; done || travis_terminate 1;
      name: 'Connection test'
    - stage: 'Push Images'
      script: curl https://raw.githubusercontent.com/tuimac/tools/master/cicd/scripts/install-buildx.sh | bash || travis_terminate 1;
      name: 'Prepare buildx'
    - script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin || travis_terminate 1;
      name: 'Docker login'
    - script: docker buildx build --platform linux/amd64,linux/arm64 -t ${IMAGE} --push . || travis_terminate 1;
      name: 'Multi-platform build and push'
