apiVersion: v1

kind: PersistentVolume
metadata:
  name: openvpn-pv
  labels:
    volume: openvpn
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  local:
    path: /kubernetes/openvpn
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openvpn-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      volume: openvpn
